### ISSUE TITLE
Could not unmarshal bytes

### ISSUE THREAD

**Issue by oggy95** [MinterTeam/minter-go-node#607]
minter node
```
panic: Could not unmarshal bytes: 7B2262617365223A2231222C22686569676874223A2233323738373838227D

goroutine 1 [running]:
github.com/tendermint/tendermint/store.LoadBlockStoreState(0x181b8a0, 0xc00018e140, 0xc00018e140, 0x0)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/store/store.go:481 +0x205
github.com/tendermint/tendermint/store.NewBlockStore(...)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/store/store.go:49
github.com/tendermint/tendermint/node.initDBs(0xc000dc6140, 0x1692098, 0xc0002bb3e8, 0x756ea103e27a31, 0xdfe346bc4db58d02, 0x0, 0x8)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/node/node.go:217 +0xa5
github.com/tendermint/tendermint/node.NewNode(0xc000dc6140, 0x1803600, 0xc00040e320, 0xc000412810, 0x17e4fa0, 0xc0004288e0, 0xc000428900, 0x1692098, 0xc000412930, 0x180ad80, ...)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/tendermint/tendermint/node/node.go:642 +0x50
github.com/MinterTeam/minter-go-node/cmd/minter/cmd.startTendermintNode(0x181bf20, 0xc0001c0d00, 0xc000dc6140, 0x180ad80, 0xc000dd6820, 0xc000dbda70, 0xd, 0x0)
        /root/go/src/github.com/MinterTeam/minter-go-node/cmd/minter/cmd/node.go:193 +0x3ed
github.com/MinterTeam/minter-go-node/cmd/minter/cmd.runNode(0x206f7a0, 0x0, 0x0)
        /root/go/src/github.com/MinterTeam/minter-go-node/cmd/minter/cmd/node.go:96 +0x314
github.com/MinterTeam/minter-go-node/cmd/minter/cmd.glob..func3(0x206f7a0, 0x20b6ad0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/MinterTeam/minter-go-node/cmd/minter/cmd/node.go:40 +0x2b
github.com/spf13/cobra.(*Command).execute(0x206f7a0, 0x20b6ad0, 0x0, 0x0, 0x206f7a0, 0x20b6ad0)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/spf13/cobra/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x206f500, 0xc000189b00, 0x15081ed, 0xe)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/spf13/cobra/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/src/github.com/MinterTeam/minter-go-node/vendor/github.com/spf13/cobra/command.go:888
main.main()
        /root/go/src/github.com/MinterTeam/minter-go-node/cmd/minter/main.go:48 +0x92e
```

minter version 2.0.0

**Comment by oggy95** [comment]
Fixed by installing v2.0.2 on fresh server.
